### ISSUE TITLE
iOS app not showing all restrooms in the database

### ISSUE THREAD

**Issue by olgrhw17** [RefugeRestrooms/refugerestrooms-ios#148]
I had this app on my old phone and it worked pretty well. It would display any additions made to the map. I had to get a new phone (with iOS 10.3.2) recently so I redownloaded the app. Now it doesn't seem to be working. A significant portion of the restrooms that I've seen added over the past few months no longer show up on the map. (It shows only about half the marked restrooms that it did earlier today when I was still using my old phone.) These restrooms still show up when searched on the website. Any ideas what's going on?

**Comment by mi-wood** [comment]
This has been an issue going on with both iOS and the web. I've seen a lot of tickets coming in from the contact form. I haven't gotten a second to look into it, but if someone else does I can help them out.

**Comment by Intimaria** [comment]
Hi, I’ve been using the app on my phone and tried to add a refuge restroom near my area, to no avail - I mean,
it said received but it didn’t
show up. 

I’d really like to add more but not sure what happened.

I wonder if the data I input ended up in the database, and just is not showing up on the map, or did it get lost into the ether? 

My “user” thinking was - “perhaps a place need to be input a few times before it shows up”, but then I saw this issue.

**Comment by hkellaway** [comment]
the iOS app has an issue in that, after adding a location, you’d have to close and reopen the app to see the newly added location. did it show up after relaunching perhaps?

**Comment by Intimaria** [comment]
Hi, no, I added it a few weeks ago. I checked back a few times since but it never showed.

**Comment by DeeDeeG** [comment]
I wonder if this has to do with switching the site/API to HTTPS.

The website was changed over to using HTTPS approximately last May, judging by re-reading this issue:
- https://github.com/RefugeRestrooms/refugerestrooms/issues/345. 

And it was set to HTTPS-only in August, I think:
- https://github.com/RefugeRestrooms/refugerestrooms/pull/362

(Narrowing this down: Would a dev with access to the DB/admin controls (to delete test restroom entries) mind if one of us added a fake restroom e.g. in Antarctica using the app, just to confirm that submissions work at all?)

**Comment by DeeDeeG** [comment]
There is a restroom near my house that shows up in restroom search on the website, but as @olgrhw17 reports, I'm not seeing a pin for it on the map of the iOS app.

@Intimaria, if you want to check if the restroom entry you made was uploaded properly, perhaps you can check at https://refugerestrooms.org, by searching its address there?

**Comment by Intimaria** [comment]
Hi, it's not there. I added the Centro Cultural Olga Vazquez in La Plata, Argentina. I could try again via the web app instead of ios. 
Nothing comes up for that city right now. It would be great to be able t oadd more as the local university also implemented unisex bathrooms recently. 

The only nearby entry is Casa Brandon which is in Buenos Aires about an hour away (was there previously), but that only comes up if I search specifically Buenos Aires. When I enable location sharing, the Casa Brandon one doesn't come up when I zoom out on the web app. 
On the web I also can't access a map view that just default shows all the entries without searching which I can on the ios, in case the search term or location is the problem.

**Comment by Intimaria** [comment]
Hi, it's not there. I could try adding some entries again via the web app instead of ios.

The only nearest entry is Casa Brandon which is in Buenos Aires (was there previously), but that only comes up if I search specifically Buenos Aires. When I enable location sharing, the Casa Brandon bathroom doesn't come up when I zoom out on the web app. 

On the web I also can't access a map view that just default shows all the entries without searching which I can on the ios, in case the search term or location is the problem.

**Comment by DeeDeeG** [comment]
We are probably going to have a new version of the iOS app out soon, since testing is going well so far.

[Also:](https://github.com/RefugeRestrooms/refugerestrooms-ios/pull/153#issuecomment-362944262)

> note: just need to take screen shots for the App Store for iPad Pro before we can attempt to submit this release to Apple

Maybe the new app version will fix the inability to submit new entries?
